apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-external-ingress
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  ingress:
    - ports:
        - port: {{ .Values.port }}
