apiVersion: apps/v1
kind: Deployment
metadata:
  name: exobrain
  labels:
    app: exobrain
# TODO: Digest from emanote container
# TODO: An ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exobrain
  template:
    metadata:
      labels:
        app: exobrain
    spec:
      containers:
        - name: emanote
          image: sridca/emanote
          ports:
            - containerPort: 80
          volumeMounts:
            - name: syncdir
              mountPath: /syncdir
          command: [ "emanote", "run", "--host=0.0.0.0", "--port=80", "--layers=/syncdir/zettelkasten" ]
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.6
          volumeMounts:
            - name: syncdir
              mountPath: /syncdir
          env:
            - name: GIT_SYNC_REPO
              value: https://github.com/huuff/exobrain.git
            - name: GIT_SYNC_BRANCH
              value: master
            - name: GIT_SYNC_DEST
              value: zettelkasten
            - name: GIT_SYNC_ROOT
              value: /syncdir
      volumes:
        - name: syncdir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: exobrain
spec:
  selector:
    app: exobrain
  type: NodePort
  ports:
    - port: 80
      nodePort: 30002
