# TODO: Try to make it run as non-root
# TODO: As chart
apiVersion: v1
kind: ConfigMap
metadata:
  name: keys-nginx-conf
data: 
  nginx.conf: |
    events {}
    http {
      server {
        root /www/keys;

        location / {
          autoindex on;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-keys
data:
  id_rsa: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC34ucjfwaqgPu7arMZxJv/6+hEIauiseJZJFfqfrd4Qn4kro0GWS0M9f/V7o/W2q8hCiwvz5YoHPT2NauPDpb1UTT9BGHk2q+hMioDYr5EXc+2NtPC8woxZalfABVwFLzzMBhDxUCg52OqPL1tLl4kBu4YCpKPOEN/pgTtiMPyjmMh53AueEy8CI2Qfm5ZpdEUsYL75vuU+FLb1RatkrsVT94qHbxBwrNu26aNwEQ5HNFHOYR0u1Jnt+K0ogJ7tavc36M9JfiY1GYdKA9NYlZnwesYYRhaJ59LQJY54KbdQpwHAhs54x7O6O71jrmgQiM+6Agy1eTOmdmnnEEbHiHF7wg0A39uc9t7iZ0oOcufrycnACVAjtkl67ch7VWUTZc5N6vCic27wupXAOlqYT1RxmpK/rhOEw/f0sIVtBPNv2Sd8w+SEpnYo9zHPzesKsRin+A5U6NL0NMYoIWxPHlutHzJDzK6z9N1Lez3h2hBReyVP8PPaZao4/cvS5r+2R0="
  id_ed25519: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIZUhSFFTnachNf82fmzzHw0jYiry/X4Mpg+H/ogn3SK"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keys
  labels:
    app: keys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keys
  template:
    metadata:
      labels:
        app: keys
    spec:
      containers:
        - name: nginx
          image: nginx:alpine@sha256:efc09388b15fb423c402f0b8b28ca70c7fd20fe31f8d7531ae1896bbb4944999
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: www-root
              mountPath: /www/keys
              readOnly: true
        - name: indexer
          image: busybox@sha256:52f431d980baa76878329b68ddb69cb124c25efa6e206d8b0bd797a828f0528e
          volumeMounts:
            - name: ssh-keys
              mountPath: /keys
            - name: www-root
              mountPath: /www/keys
          command:
            - "/bin/sh"
            - "-c"
            - | 
              while true; 
              do 
                cp /keys/* /www/keys
                rm -f /www/keys/all
                # Merge all keys
                for key in /www/keys/*;
                do
                  echo "$(cat $key)" >> /www/keys/all
                done
                sleep 60
              done
          securityContext:
            readOnlyRootFilesystem: true
      automountServiceAccountToken: false
      volumes:
        - name: nginx-conf
          configMap:
            name: keys-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: ssh-keys
          configMap:
            name: ssh-keys
        - name: www-root
          emptyDir: {}
