# TODO: helm chart

apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  clusterIP: None
  selector:
    app:
      test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 2
  serviceName: test
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - test
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: test
          image: odise/busybox-curl
          command: [ "sleep", "3600" ]
          resources:
            requests:
              cpu: "15m"
              memory: "30Mi"
            limits:
              cpu: "15m"
              memory: "30Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
      automountServiceAccountToken: false
