apiVersion: v1
kind: Secret
metadata:
  name: readonly-user-token
  namespace: observability
  annotations:
    kubernetes.io/service-account.name: {{ .Values.accountName }}
    kubernetes.io/service-account.namespace: observability
type: kubernetes.io/service-account-token
