apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        "kyverno.haff.xyz/ignore-always-pull-images": "yes"
    spec:
      containers:
        - name: git-sync
          image: "k8s.gcr.io/git-sync:v{{ .Values.gitSync.version }}"
          volumeMounts:
            - name: syncdir
              mountPath: /syncdir
          env:
            - name: GIT_SYNC_WAIT
              value: {{ .Values.gitSync.refreshPeriod | quote }}
            - name: GIT_SYNC_REPO
              value: {{ .Values.gitSync.repo }}
            - name: GIT_SYNC_BRANCH
              value: {{ .Values.gitSync.branch }}
            - name: GIT_SYNC_DEST
              value: zettelkasten
            - name: GIT_SYNC_ROOT
              value: /syncdir
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          resources:
            {{- toYaml .Values.gitSync.resources | nindent 12 }}
          lifecycle:
            postStart:
              exec:
                command: 
                  - "sh"
                  - "-c"
                  - | 
                    until [ -e /syncdir/zettelkasten ]; do 
                      sleep 1
                    done
        - name: emanote
          image: sridca/emanote@{{ .Values.emanote.digest }}
          ports:
            - containerPort: {{ .Values.emanote.port }}
          volumeMounts:
            - name: syncdir
              mountPath: /syncdir
              readOnly: true
          command:
            - "emanote"
            - "run"
            - "--host=0.0.0.0"
            - "--port={{ .Values.emanote.port }}"
            - "--layers=/syncdir/zettelkasten"
            - "--verbose"
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.emanote.port }}
            initialDelaySeconds: {{ .Values.emanote.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.emanote.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.emanote.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.securityContext.user }}
        runAsGroup: {{ .Values.securityContext.group }}
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      volumes:
        - name: syncdir
          emptyDir: {}
