apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: emanote
          image: sridca/emanote@{{ .Values.emanote.digest }}
          ports:
            - containerPort: {{ .Values.emanote.port }}
          volumeMounts:
            - name: syncdir
              mountPath: /syncdir
          command:
            - "emanote"
            - "run"
            - "--host=0.0.0.0"
            - "--port={{ .Values.emanote.port }}"
            - "--layers=/syncdir/zettelkasten"
            - "--verbose"
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.emanote.port }}
            initialDelaySeconds: {{ .Values.emanote.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.emanote.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.emanote.resources | nindent 12 }}
          # TODO: Whole git-sync container as a helper function
        - name: git-sync
          image: "k8s.gcr.io/git-sync:v{{ .Values.gitSync.version }}"
          volumeMounts:
            - name: syncdir
              mountPath: /syncdir
          env:
            - name: GIT_SYNC_WAIT
              value: {{ .Values.gitSync.refreshPeriod | quote }}
            - name: GIT_SYNC_REPO
              value: {{ .Values.gitSync.repo }}
            - name: GIT_SYNC_BRANCH
              value: {{ .Values.gitSync.branch }}
            - name: GIT_SYNC_DEST
              value: zettelkasten
            - name: GIT_SYNC_ROOT
              value: /syncdir
          resources:
            {{- toYaml .Values.gitSync.resources | nindent 12 }}

      initContainers:
        - name: git-init-sync
          image: "k8s.gcr.io/git-sync:v{{ .Values.gitSync.version }}"
          volumeMounts:
            - name: syncdir
              mountPath: /syncdir
          env:
            - name: GIT_SYNC_REPO
              value: {{ .Values.gitSync.repo }}
            - name: GIT_SYNC_BRANCH
              value: {{ .Values.gitSync.branch }}
            - name: GIT_SYNC_ROOT
              value: /syncdir
            - name: GIT_SYNC_DEST
              value: zettelkasten
            - name: GIT_SYNC_ONE_TIME
              value: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.securityContext.user }}
        runAsGroup: {{ .Values.securityContext.group }}
      volumes:
        - name: syncdir
          emptyDir: {}
