replicas: 1

emanote:
  digest: "sha256:97cf33f0caa2295ed3bd6abbb7c6a52f83d58f40bef75402337f0ed92aa34d3c"
  port: "8080"
  resources:
    requests:
      cpu: ""
      memory: ""
    limits:
      cpu: ""
      memory: ""
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
gitSync:
  version: 3.1.6
  repo: ""
  branch: master
  refreshPeriod: "60"
  resources:
    requests:
      cpu: ""
      memory: ""
    limits:
      cpu: ""
      memory: ""
tls:
  enabled: true
  clusterIssuer: ""
  secretName: ""
ingress:
  enabled: true
  class: "nginx"
  host: ""
securityContext:
  user: 1000
  group: 1000

verticalPodAutoscaler:
  enabled: true
  mode: "Auto"
