git:
  repo: ""
  branch: master
  refreshPeriod: "60"
tls:
  clusterIssuer: ""
  secretName: ""
ingress:
  class: "nginx"
  host: ""

name: "zettelkasten"
replicas: 1
digest: "sha256:97cf33f0caa2295ed3bd6abbb7c6a52f83d58f40bef75402337f0ed92aa34d3c"
port: "8080"
