apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name }}-nginx-conf
data: 
  nginx.conf: |
    events {}
    http {
      server {
        listen {{ .Values.port }};
        root /www/keys;

        location / {
          autoindex on;
        }
      }
    }

