apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name }}-nginx-conf
data: 
  nginx.conf: |
    events {}
    pid /tmp/nginx.pid;
    http {
      server {
        listen {{ .Values.port }};
        root /www/keys;

        client_body_temp_path /tmp/client_temp;
        proxy_temp_path /tmp/proxy_temp_path;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;

        location / {
          autoindex on;
        }
      }
    }

