# XXX: A sample nginx deployment to test my Kyverno policies
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      annotations:
        "kyverno.haff.xyz/ignore-dont-run-as-root": "yes"
        "kyverno.haff.xyz/ignore-make-root-fs-readonly": "yes"
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
      automountServiceAccountToken: false
