digest: sha256:09c79bc1e4032c7c3b1b808cfbe384226cb5cd27b86f2cb0876b7d20e1a8b3d4
user: 7890
group: 7890
port: 8080

database:
  dialect: "sqlite3"
  host: ""
  port: ""
  name: ""
  credentials:
    secretName: ""
    userKey: ""
    passwordKey: ""
  pod:
    labelKey: ""
    labelValue: ""

defaultuser:
  name: admin
  pass: admin

resources:
  requests:
    cpu: ""
    memory: ""
  limits:
    cpu: ""
    memory: ""

initContainer:
  digest: sha256:52f431d980baa76878329b68ddb69cb124c25efa6e206d8b0bd797a828f0528e
  resources:
    requests:
      cpu: "10m"
      memory: "10Mi"
    limits:
      cpu: "10m"
      memory: "10Mi"

verticalPodAutoscaler:
  enabled: true
  mode: "Auto"
