repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

releases:
  - name: metrics-server
    namespace: observability
    chart: metrics-server/metrics-server
    set:
      - name: args
        values: [ "--kubelet-insecure-tls" ] # TODO: Fix certs
  - name: kubernetes-dashboard
    namespace: observability
    chart: kubernetes-dashboard/kubernetes-dashboard
    set:
      - name: metricsScraper.enabled
        value: true
  - name: observability-user
    namespace: observability
    chart: ./observability-service-account
