repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: metrics-server
    namespace: observability
    chart: metrics-server/metrics-server
    set:
      - name: args
        values: [ "--kubelet-insecure-tls" ] # TODO: Fix certs
  - name: kubernetes-dashboard
    namespace: observability
    chart: kubernetes-dashboard/kubernetes-dashboard
    set:
      - name: metricsScraper.enabled
        value: true
  - name: readonly-user
    namespace: observability
    chart: incubator/raw
    values:
      - resources:
        - apiVersion: v1
          kind: ServiceAccount
          metadata:
            namespace: observability
            name: readonly-user
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: readonly-role
          rules:
            - apiGroups: ["", "extensions", "apps"]
              resources: ["deployments", "pods", "services", "namespaces", "nodes", "events", "replicasets", "daemonsets"]
              verbs: ["get", "list", "watch"]
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: readonly-role-binding
            namespace: observability
          subjects:
            - kind: ServiceAccount
              name: readonly-user
              namespace: observability
              apiGroup: ""
          roleRef:
            kind: ClusterRole
            name: readonly-role
            apiGroup: rbac.authorization.k8s.io
        - apiVersion: v1
          kind: Secret
          metadata:
            name: readonly-user-token
            namespace: observability
            annotations:
              kubernetes.io/service-account.name: readonly-user
              kubernetes.io/service-account.namespace: observability
          type: kubernetes.io/service-account-token
