repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

# TODO: Currently only using it through port-forwarding... use an ingress
releases:
  - name: kube-prometheus
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
