repositories:
  - name: postgres-operator-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  - name: postgres-operator-ui-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui

releases:
    # Note that the helm chart already has some sane defaults like
    # running as non-root (but do they work, actually?)
  - name: postgres-operator
    chart: postgres-operator-charts/postgres-operator
    namespace: operators
    values:
      - ./values.yaml
  - name: postgres-operator-ui
    chart: postgres-operator-ui-charts/postgres-operator-ui
    namespace: operators
