verticalPodAutoscaler:
  enabled: true
  mode: "Auto"

resources:
  requests:
    cpu: ""
    memory: ""
  limits:
    cpu: ""
    memory: ""


digest: "sha256:81372de8c566f2d731bde924bed45230018e6d7c21d051c15e283eb8e06dfa2d"

refreshDelaySeconds: 60
watchedUrl: ""

securityContext:
  user: 8008
  group: 8008

gotify:
  url: ""
  token:
    secretName: ""
    keyName: ""
