repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    set:
      - name: "controller.hostNetwork"
        value: true
      - name: "controller.kind"
        value: "DaemonSet"

