apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: app-ingress
spec:
  rules:
  - host: exobrain.haff.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: exobrain
            port:
              number: 80
