apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: dont-allow-privilege-escalation
spec:
  validationFailureAction: enforce
  rules:
    - name: dont-allow-privilege-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "`allowPrivilegeEscalation` should be `false`"
        pattern:
          metadata:
            <(annotations):
              "X(kyverno.haff.xyz/ignore-dont-allow-privilege-escalation)": "?*"
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
