{{-  $policyName := "dont-allow-privilege-escalation" -}}

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $policyName }}
spec:
  validationFailureAction: enforce
  rules:
    - name: {{ $policyName }}
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces: {{- toYaml .Values.namespaces | nindent 14 }}
      validate:
        message: |
          `allowPrivilegeEscalation` should be `false`
          If the user namespace is shared between the host and the container, escalating privileges in the container equals escalating privileges on the host. Compounded with a container escape vulnerability, this setting can be devastating.
        pattern:
          metadata:
            <(annotations):
              "X(kyverno.haff.xyz/ignore-{{ $policyName }})": "?*"
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
