{{- $policyName := "dont-run-as-root" -}}

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $policyName }}
spec:
  validationFailureAction: enforce
  rules:
    - name: {{ $policyName }}
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: |
          `runAsNonRoot` should be `true`.
          Since the user namespace is shared with the host, without this setting, an intruder is only one container escape vulnerability from gaining full superuser control on the node.
        pattern:
          metadata:
            <(annotations):
              "X(kyverno.haff.xyz/ignore-{{ $policyName }}": "?*"
          spec:
            securityContext:
              runAsNonRoot: true
