{{-  $policyName := "dont-allow-privilege-escalation" -}}

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $policyName }}
spec:
  validationFailureAction: enforce
  rules:
    - name: {{ $policyName }}
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "`allowPrivilegeEscalation` should be `false`"
        pattern:
          metadata:
            <(annotations):
              "X(kyverno.haff.xyz/ignore-{{ $policyName }})": "?*"
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
