apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: dont-automount-service-account-token
spec:
  validationFailureAction: enforce
  rules:
  - name: dont-automount-service-account-token
    match:
      any:
        - resources:
            kinds:
            - Pod
            selector:
              matchExpressions:
                - { key: "kyverno.haff.xyz/ignore-dont-automount-service-account-token", operator: "DoesNotExist" }
    validate:
      message: |
        `automountServiceAccountToken` should be disabled unless the pod requires access to the kubernetes API
      pattern:
        spec:
          automountServiceAccountToken: false
