apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: dont-run-as-root
spec:
  validationFailureAction: enforce
  rules:
    - name: dont-run-as-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "`runAsNonRoot` should be `true`"
        pattern:
          metadata:
            <(annotations):
              "X(kyverno.haff.xyz/ignore-dont-run-as-root)": "?*"
          spec:
            securityContext:
              runAsNonRoot: true
